### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Bike** [s-expressionists/Maclina#1]
Any objection to giving this a BSD-2 license? @karlosz @yitzchak @drmeister who i have marked as authors of various code here

The ANSI tests I copied in are already under MIT and have their own license file.

**Comment by karlosz** [comment]
Hi, license is OK.

I would like to see that the old design notes I wrote up and the virtual machine description we worked on get put into this repository somehow though. They can just be markdown files. We don't necessarily need to update them immediately; however it's better than nothing.

**Comment by Bike** [comment]
Yeah, I can put them in. I wrote up a new  "formal" description in MACHINE.md.

**Comment by yitzchak** [comment]
I have no objections.

**Comment by drmeister** [comment]
I have no objections to a BSD-2 license.
